[theme]
base="dark"
primaryColor = "#1f77b4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2230"
textColor = "#FFFFFF"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501
address = "0.0.0.0"

[global]
# reduce telemetry
send_usage_stats = false
